#!/bin/bash
getopts n: opt
baseURL="http://api.urbandictionary.com/v0/"
if [[ -z $3 ]]; then
	term=$1
else
	term=$3
fi

if [[ "$term" == "random" ]]; then
	lookup="$(curl -s "$baseURL"random | python -mjson.tool)"
else
	#term=$(echo "$term" | sed 's/ /\%20/')
	term="${term// /%20}"
	lookup="$(curl -s "$baseURL"define?term="$term" | python -mjson.tool)"
fi
#max_defs="$(echo "$lookup" | grep -c "\"definition\":")"
max_defs="$(grep -c "\"definition\":" <<< "$lookup")"
result_type="$(grep -oP '(?<=\"result_type\": )\".*' <<< "$lookup" | sed -n "1 p" | cut -d\" -f2)"

print_def() {

	for ((i=1;i<="$OPTARG";i++)); do
		word="$(grep -oP '(?<=\"word\": )\".*' <<< "$lookup" | sed -n "$i p")"
		def="$(grep -oP '(?<=\"definition\": )\".*' <<< "$lookup" | sed -n "$i p")"
		author="$(grep -oP '(?<=\"author\": )\".*' <<< "$lookup" | sed -n "$i p ")"
		example="$(grep -oP '(?<=\"example\": )\".*' <<< "$lookup" | sed -n "$i p ")"
		echo -e "\nWord: $word"
		echo -e "\nDefinition:"
		echo -E "${def:0:${#def}-2}" | sed -r 's/\\\S//g'| fmt -t
		echo -e "\nAuthor:"
		echo -E "${author:0:${#author}-2}" | sed -r 's/\\\S//g'
		echo -e "\nExample:"
		echo -E "${example:0:${#example}-2}" | sed -r 's/\\\S//g' | fmt -t
		echo "_________________________________________________________________________"
	done
}
if [[ ! "$result_type" == "no_results" ]]; then
	if [[ "$OPTARG" -gt 1 ]]; then
		if [[ "$OPTARG" -gt "$max_defs" ]]; then
			OPTARG="$max_defs"
		fi
		for ((i=0;i<"$OPTARG";i++)); do
			print_def
		done
	else
		OPTARG=1
		print_def
	fi
else
	echo -e "\nNo results found for \"$term\".\n"
fi
